name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: StaticDeploy
    env:
      STATICDEPLOY_API_URL: ${{secrets.STATICDEPLOY_API_URL}}
      STATICDEPLOY_API_TOKEN: ${{secrets.STATICDEPLOY_API_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy bundle
        run: yarn deploy:bundle
      - name: Deploy bundle
        run: yarn deploy:entrypoint
