name: QA

on: [push, pull_request]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Check formatting
        run: yarn check-formatting
      - name: Build
        run: yarn build
